name: parky
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  internet_connection_checker: ^3.0.1
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.5.3
  page_transition: ^2.2.1
  animated_custom_dropdown: ^3.1.1
  sqflite: ^2.4.2
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  injectable_generator: ^2.6.2
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4
  freezed: ^3.0.3
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: "Poppins"
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
